spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 55397490245-vrea6e25raq9kg7rh729gqkp50abe2kt.apps.googleusercontent.com
            clientSecret: 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
#            scope:
#              - user:email
#              - read:user
  datasource:
    url: jdbc:h2:mem:testdb
    username: bank
    password: bank
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

